language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed lamtiendinh/udagram-api-feed:latest
  - docker tag udagram-api-user lamtiendinh/udagram-api-user:latest
  - docker tag udagram-frontend lamtiendinh/udagram-frontend:latest
  - docker tag udagram-reverseproxy lamtiendinh/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lamtiendinh/udagram-api-feed
  - docker push lamtiendinh/udagram-api-user
  - docker push lamtiendinh/udagram-frontend
  - docker push lamtiendinh/udagram-reverseproxy